analyzer:
  exclude:
    - 'build/**'
    - 'doc/api/**'
    - 'lib/bower/**'
    - 'last_prod/**'
    - 'third_party/pkg/**'

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
