targets:
  $default:
    sources:
      exclude:
      - web/example/dart_codelab/**
      - web/example/flutter_codelab/**
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          - --minify
          - --fast-startup
      json_serializable:
        options:
