targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
          - web/**.dart
          exclude:
          - web/example/codelabs/**.dart
        options:
          dart2js_args:
          - --minify
          - --fast-startup
      json_serializable:
        generate_for:
          include:
          - lib/**.dart
          exclude:
          - web/example/codelabs/**.dart
