name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  codemirror: ^0.4.1
  haikunator: ^0.1.0
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.9.0 <0.12.0'
  markdown: ^2.0.0
  route_hierarchical: ^0.7.0
dev_dependencies:
  git: any
  grinder: ^0.8.0
  test: ^0.12.0
  yaml: any
