name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'
dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  codemirror: '^0.4.2+5.13.4'
  # TODO(jcollins-g): return to haikunator pub package after it is
  # published with https://github.com/Atrox/haikunatordart/pull/1
  #haikunator: ^0.1.0
  haikunator:
    path: third_party/pkg/haikunatordart/
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.9.0 <0.12.0'
  markdown: ^2.0.0
  route_hierarchical:
    path: third_party/pkg/route.dart/
dev_dependencies:
  build_runner: any
  build_web_compilers: any
  collection: ^1.14.10
  dhttpd: any
  git: any
  grinder: ^0.8.0
  test: ^1.3.4
  tuneup: any
  yaml: any
