name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  codemirror: ^0.6.0-0
  fluttering_phrases: ^0.3.1
  http: ^0.13.3
  json_annotation: ^4.0.1
  logging: ^1.0.1
  markdown: ^4.0.0
  meta: ^1.2.4
  protobuf: ^2.0.0
  route_hierarchical:
    path: third_party/pkg/route.dart/
  split: ^0.0.6
  html_unescape: ^2.0.0
  sass_builder: ^2.1.0
  mdc_web: ^0.5.0-pre
  yaml: ^3.1.0
  checked_yaml: ^2.0.1
  js: ^0.6.0
  stream_transform: ^2.0.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.14.10
  git: ^2.0.0
  grinder: ^0.9.0
  json_serializable: ^4.1.3
  pedantic: ^1.11.0
  shelf: ^1.1.4
  shelf_static: ^1.0.0
  test: ^1.15.7
